services:
  server:
    build:
      context: .
      target: app
      args:
        TEXT_ADVENTURES_ASSET_VERSION: ${TEXT_ADVENTURES_ASSET_VERSION:-dev}
    image: text_adventures-server:${TEXT_ADVENTURES_ASSET_VERSION:-latest}
    environment:
      TEXT_ADVENTURES_HOST: 0.0.0.0
      TEXT_ADVENTURES_PORT: 4567
      TEXT_ADVENTURES_ASSET_VERSION: ${TEXT_ADVENTURES_ASSET_VERSION:-dev}

  web:
    build:
      context: .
      target: web
    image: text_adventures-web:${TEXT_ADVENTURES_ASSET_VERSION:-latest}
    depends_on:
      - server
    networks:
      default:
        aliases:
          - text-adventures
      cloudflare:
        aliases:
          - text-adventures

networks:
  cloudflare:
    external: true
