services:
  server:
    build:
      context: .
      args:
        TEXT_ADVENTURES_ASSET_VERSION: ${TEXT_ADVENTURES_ASSET_VERSION:-dev}
    image: text_adventures:${TEXT_ADVENTURES_ASSET_VERSION:-latest}
    environment:
      TEXT_ADVENTURES_HOST: 0.0.0.0
      TEXT_ADVENTURES_PORT: 4567
      TEXT_ADVENTURES_ASSET_VERSION: ${TEXT_ADVENTURES_ASSET_VERSION:-dev}
    networks:
      default:
        aliases:
          - text-adventures
      cloudflare:
        aliases:
          - text-adventures
    ports:
      - "3000:4567"

networks:
  cloudflare:
    external: true
