require 'spec_helper'

RSpec.describe "Frontend assets" do
  let(:root) { File.expand_path("../..", __dir__) }
  let(:public_root) { File.join(root, "public") }

  it "checks in the HTML, CSS, and JavaScript frontend files" do
    expect(File).to exist(File.join(public_root, "index.html"))
    expect(File).to exist(File.join(public_root, "styles.css"))
    expect(File).to exist(File.join(public_root, "app.js"))
    expect(File).to exist(File.join(public_root, "map_renderer.js"))
    expect(File).to exist(File.join(public_root, "assets/tilesets/original-dungeon-tileset.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/village-hub.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/tavern-interior.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/merchant-district.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/blacksmith-workshop.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/armorsmith-shop.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/temple-sanctuary.png"))
    expect(File).to exist(File.join(public_root, "assets/figma/dungeon-terminal-reference.png"))
  end

  it "wires the frontend to the JSON API endpoints" do
    html = File.read(File.join(public_root, "index.html"))
    javascript = File.read(File.join(public_root, "app.js"))
    renderer = File.read(File.join(public_root, "map_renderer.js"))
    styles = File.read(File.join(public_root, "styles.css"))

    expect(html).to include('<link rel="stylesheet" href="/styles.css">')
    expect(html).to include('<canvas')
    expect(html).to include('id="location-art"')
    expect(html).to include('src="/assets/locations/village-hub.png"')
    expect(html).to include('id="map-canvas"')
    expect(html).to include('<span>STATUS</span>')
    expect(html).to include('id="status-value"')
    expect(html).to include('── CLASSES ──')
    expect(html).to include('id="class-output"')
    expect(html).to include('── ENEMY ──')
    expect(html).to include('id="enemy-panel"')
    expect(html).to include('id="enemy-health-bar"')
    expect(html).to include('id="enemy-status-value"')
    expect(html).not_to include('class="run-stats"')
    expect(html).not_to include('class="attribute-grid"')
    expect(html).to include('<script src="/map_renderer.js"></script>')
    expect(html).to include('<script src="/app.js"></script>')
    expect(javascript).to include('fetch("/games"')
    expect(javascript).to include('fetch(`/games/${this.gameId}/commands`')
    expect(javascript).to include('state.scene === "ruins" && state.dungeon?.map?.length')
    expect(javascript).to include('showCanvasMap(state.dungeon)')
    expect(javascript).to include('mapRows.join("\\n")')
    expect(javascript).to include('dungeonMapRenderer.render(mapRows, { enemies: dungeon.visible_enemies || [] })')
    expect(javascript).to include('DungeonMapRenderer.create(elements.mapCanvas)')
    expect(javascript).to include('function showCanvasMap(dungeon)')
    expect(javascript).to include('function showTextMap()')
    expect(javascript).to include('function showLocationArt(scene)')
    expect(javascript).to include('const LOCATION_ARTS')
    expect(javascript).to include('"/assets/locations/village-hub.png"')
    expect(javascript).to include('"/assets/locations/tavern-interior.png"')
    expect(javascript).to include('"/assets/locations/blacksmith-workshop.png"')
    expect(javascript).to include('"/assets/locations/armorsmith-shop.png"')
    expect(javascript).to include('"/assets/locations/temple-sanctuary.png"')
    expect(javascript).to include('LOCATION_ARTS[state.scene]')
    expect(javascript).to include('"has-location-art"')
    expect(javascript).to include('function isLoggableLine(line)')
    expect(javascript).to include('let openingLogLines = []')
    expect(javascript).to include('const historyLines = history.flatMap(entry => entry.lines)')
    expect(javascript).to include('const sourceLines = [...openingLogLines, ...historyLines]')
    expect(javascript).to include('function quickCommandsFor(state)')
    expect(javascript).to include('function ruinsCommands(state)')
    expect(javascript).to include('["↑", "go up", null, "Go north"]')
    expect(javascript).to include('["→", "go right", null, "Go east"]')
    expect(javascript).to include('button.setAttribute("aria-label", accessibleLabel)')
    expect(javascript).to include('function inputModeCommand(state)')
    expect(javascript).to include('selectTab("inventory")')
    expect(javascript).to include('function selectTab(name)')
    expect(javascript).to include('state.dungeon?.nearby_loot')
    expect(javascript).to include('Cast ${firstDamageSpell.display_name}')
    expect(javascript).to include('state.pending?.confirmation')
    expect(javascript).to include('function suggestedItemCommands(player)')
    expect(javascript).to include('equippedNames.includes(item.name)')
    expect(javascript).to include('function updateCommandPlaceholder(state)')
    expect(javascript).to include('const commandHistory')
    expect(javascript).to include('function recordCommand(command)')
    expect(javascript).to include('function recallCommand(direction)')
    expect(javascript).to include('event.key === "ArrowUp"')
    expect(javascript).to include('event.key === "ArrowDown"')
    expect(javascript).to include('elements.statusValue.classList.toggle("status-alert"')
    expect(javascript).to include('elements.statusValue.classList.toggle("status-clear"')
    expect(javascript).to include('renderClassProgress(player.skills)')
    expect(javascript).to include('function renderClassProgress(skills = {})')
    expect(javascript).to include('plainAsciiBar(skill.xp, skill.next_level_xp)')
    expect(javascript).to include('row.className = "class-row"')
    expect(javascript).to include('function plainAsciiBar(current, max)')
    expect(javascript).to include('function renderEnemyStatus(battle)')
    expect(javascript).to include('elements.enemyPanel.classList.toggle("hidden", !enemy)')
    expect(javascript).not_to include('BTTL ${battle}')
    expect(javascript).not_to include('MODE ${state.input_mode.toUpperCase()}')
    expect(javascript).to include('locationPanels')
    expect(javascript).to include('/^[?#.xE@]+$/')
    expect(styles).to include('"https://fonts.googleapis.com/css2?family=VT323&display=swap"')
    expect(styles).to include('--mono: "VT323"')
    expect(styles).to include('.status-row')
    expect(styles).to include('.status-alert')
    expect(styles).to include('.class-output')
    expect(styles).to include('.class-row')
    expect(styles).to include('.class-xp')
    expect(styles).to include('.enemy-panel')
    expect(styles).to include('.hidden')
    expect(styles).not_to include('.run-stats')
    expect(styles).not_to include('.attribute-grid')
    expect(renderer).to include('globalThis.DungeonMapRenderer')
    expect(renderer).to include('"/assets/tilesets/original-dungeon-tileset.png"')
    expect(renderer).to include('"#": "wall"')
    expect(renderer).to include('".": "floor"')
    expect(renderer).to include('" ": "floor"')
    expect(renderer).to include('"?": "fog"')
    expect(renderer).to include('"x": "player"')
    expect(renderer).to include('"/assets/enemies/enemies.json"')
    expect(renderer).to include('"E": "floor"')
    expect(renderer).to include('"@": "lootBag"')
    expect(renderer).to include('function drawFog(context, x, y)')
    expect(renderer).to include('drawFog(context, x, y)')
    expect(renderer).to include('function drawEnemies(context, renderer, enemyImages, enemies)')
    expect(renderer).to include('image.src = entry.sprite')
  end
end
