require 'spec_helper'

RSpec.describe "Frontend assets" do
  let(:root) { File.expand_path("../..", __dir__) }
  let(:public_root) { File.join(root, "frontend", "public") }

  it "checks in the HTML, CSS, and JavaScript frontend files" do
    expect(File).to exist(File.join(public_root, "index.html"))
    expect(File).to exist(File.join(public_root, "styles.css"))
    expect(File).to exist(File.join(public_root, "app.js"))
    expect(File).to exist(File.join(public_root, "map_renderer.js"))
    expect(File).to exist(File.join(public_root, "assets/tilesets/original-dungeon-tileset.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/village-hub.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/tavern-interior.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/merchant-district.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/blacksmith-workshop.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/armorsmith-shop.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/temple-sanctuary.png"))
    expect(File).to exist(File.join(public_root, "assets/figma/dungeon-terminal-reference.png"))
  end

  it "wires the frontend to the JSON API endpoints" do
    html = File.read(File.join(public_root, "index.html"))
    javascript = File.read(File.join(public_root, "app.js"))
    renderer = File.read(File.join(public_root, "map_renderer.js"))
    styles = File.read(File.join(public_root, "styles.css"))

    expect(html).to include('<link rel="stylesheet" href="/styles.css">')
    expect(html).to include('<canvas')
    expect(html).to include('id="location-art"')
    expect(html).to include('src="/assets/locations/village-hub.png"')
    expect(html).to include('id="map-canvas"')
    expect(html).to include('class="map-zoom-controls"')
    expect(html).to include('id="auto-speed-1"')
    expect(html).to include('id="auto-speed-2"')
    expect(html).to include('id="auto-speed-3"')
    expect(html).to include('data-auto-speed="3"')
    expect(html).to include('id="map-zoom-in"')
    expect(html).to include('id="map-zoom-out"')
    expect(html).to include('<span>STATUS</span>')
    expect(html).to include('id="status-value"')
    expect(html).to include('── CLASSES ──')
    expect(html).to include('id="class-output"')
    expect(html).to include('═══ COMANDOS ══')
    expect(html).to include('id="auto-explore-toggle"')
    expect(html).to include('id="auto-explore-status"')
    expect(html).to include('Auto: stopped')
    expect(html).to include('id="context-commands"')
    expect(html).to include('id="shop-overlay"')
    expect(html).to include('id="player-trade-list"')
    expect(html).to include('id="merchant-trade-list"')
    expect(html).to include('id="trade-confirm"')
    expect(html).to include('CURRENT GOLD')
    right_column = html.index('<aside class="right-column">')
    inventory_panel = html.index('class="terminal-panel inventory-panel"', right_column)
    commands_panel = html.index('class="terminal-panel commands-panel"', right_column)
    expect(commands_panel).to be > inventory_panel
    expect(html).to include('── ENEMY ──')
    expect(html).to include('id="enemy-panel"')
    expect(html).to include('id="enemy-health-bar"')
    expect(html).to include('id="enemy-status-value"')
    expect(html).not_to include('id="top-mode"')
    expect(html).not_to include('MODO:')
    expect(html).not_to include('[H]abilidades')
    expect(html).not_to include('id="skills-tab"')
    expect(html).not_to include('class="run-stats"')
    expect(html).not_to include('class="attribute-grid"')
    expect(html).to include('<script src="/map_renderer.js"></script>')
    expect(html).to include('<script src="/app.js"></script>')
    expect(javascript).to include('fetch("/api/games"')
    expect(javascript).to include('const SAVED_GAME_ID_KEY = "text_adventures.game_id"')
    expect(javascript).to include('const AUTO_EXPLORE_MEMORY_KEY_PREFIX = "text_adventures.auto_explore."')
    expect(javascript).to include('async fetchGame(gameId)')
    expect(javascript).to include('async deleteGame(gameId)')
    expect(javascript).to include('window.localStorage.getItem(SAVED_GAME_ID_KEY)')
    expect(javascript).to include('window.localStorage.setItem(SAVED_GAME_ID_KEY, gameId)')
    expect(javascript).to include('window.localStorage.removeItem(SAVED_GAME_ID_KEY)')
    expect(javascript).to include('function autoExploreMemoryKey(gameId = api.gameId)')
    expect(javascript).to include('function restoreAutoExploreMemory(state)')
    expect(javascript).to include('function saveAutoExploreMemory()')
    expect(javascript).to include('if (state?.scene !== "ruins")')
    expect(javascript).to include('forgetAutoExploreMemory(api.gameId)')
    expect(javascript).to include('function urlGameId()')
    expect(javascript).to include('window.location.pathname.match(/^\\/game\\/([^/]+)$/)')
    expect(javascript).to include('function updateGameUrl(gameId)')
    expect(javascript).to include('url.pathname = `/game/${encodeURIComponent(gameId)}`')
    expect(javascript).to include('url.search = ""')
    expect(javascript).to include('window.history.replaceState({}, "", url)')
    expect(javascript).to include('const gameId = urlGameId() || savedGameId()')
    expect(javascript).to include('async function initialGamePayload()')
    expect(javascript).to include('new WebSocket(`${protocol}//${window.location.host}/ws?game_id=${encodeURIComponent(gameId)}`)')
    expect(javascript).to include('connectGame(gameId)')
    expect(javascript).to include('sendAction(action)')
    expect(javascript).to include('function actionFromCommand(command)')
    expect(javascript).to include('function actionCommandError(message, code = "invalid_action")')
    expect(javascript).to include('function handleActionCommandError(error)')
    expect(javascript).to include('const action = actionFromCommand(command)')
    expect(javascript).to include('await api.sendAction(action)')
    expect(javascript).to include('if (state.battle?.active) return battleCommands(state)')
    expect(javascript).to include('function battleCommands(state)')
    expect(javascript).to include('["Atacar", "attack", "primary"]')
    expect(javascript).not_to include('const payload = await api.sendAction(actionFromCommand(command))')
    expect(javascript).not_to include('/commands')
    expect(javascript).to include('function handleSocketMessage(event)')
    expect(javascript).to include('if (message.type === "state")')
    expect(javascript).to include('if (message.type === "events")')
    expect(javascript).to include('function mergeStatePatch(state, patch)')
    expect(javascript).to include('function webSocketActionPayload(action)')
    expect(javascript).to include('return { type: "action", action: type, ...fields }')
    expect(javascript).to include('const SOCKET_RECONNECT_INTERVAL_MS = 10_000')
    expect(javascript).to include('const SOCKET_RECONNECT_TIMEOUT_MS = 120_000')
    expect(javascript).to include('const AUTO_EXPLORE_SPEEDS = [1, 2, 3]')
    expect(javascript).to include('function startSocketReconnect()')
    expect(javascript).to include('api.reconnectTimer = setTimeout(attemptSocketReconnect, SOCKET_RECONNECT_INTERVAL_MS)')
    expect(javascript).to include('function attemptSocketReconnect()')
    expect(javascript).to include('if (!autoExplore.enabled && autoExplore.status === "Auto: offline") updateAutoExploreStatus("Auto: stopped")')
    expect(javascript).to include('function failSocketReconnect()')
    expect(javascript).to include('Connection lost. Could not reconnect after 2 minutes. Type new to start a new game.')
    expect(javascript).to include('function socketReconnectInProgress()')
    expect(javascript).to include('function startNewGame()')
    expect(javascript).to include('command.trim().toLowerCase() === "new"')
    expect(javascript).to include('state.scene === "ruins" && state.dungeon?.viewport')
    expect(javascript).to include('showCanvasMap(state)')
    expect(javascript).to include('mapRows.join("\\n")')
    expect(javascript).to include('dungeonMapRenderer.render(dungeon.viewport, { playerDead: playerDefeated(state) })')
    expect(javascript).to include('function playerDefeated(state)')
    expect(javascript).to include('["Recarregar", "reload", "primary"]')
    expect(javascript).to include('function textRowsFromViewport(viewport)')
    expect(javascript).to include('DungeonMapRenderer.create(elements.mapCanvas)')
    expect(javascript).to include('const DUNGEON_MAP_BASE_ZOOM = 1.3')
    expect(javascript).to include('const LOCATION_ART_BASE_ZOOM = 1.12')
    expect(javascript).to include('const MAP_ZOOM_STEP = 0.12')
    expect(javascript).to include('let mapZoom = 1')
    expect(javascript).to include('function showCanvasMap(state)')
    expect(javascript).to include('function showTextMap()')
    expect(javascript).to include('function showLocationArt(scene)')
    expect(javascript).to include('function setMapZoom(nextZoom)')
    expect(javascript).to include('function adjustMapZoom(direction)')
    expect(javascript).to include('elements.mapZoomIn.addEventListener("click", () => adjustMapZoom(1))')
    expect(javascript).to include('elements.mapZoomOut.addEventListener("click", () => adjustMapZoom(-1))')
    expect(javascript).to include('const LOCATION_ARTS')
    expect(javascript).to include('"/assets/locations/village-hub.png"')
    expect(javascript).to include('"/assets/locations/tavern-interior.png"')
    expect(javascript).to include('"/assets/locations/blacksmith-workshop.png"')
    expect(javascript).to include('"/assets/locations/armorsmith-shop.png"')
    expect(javascript).to include('"/assets/locations/temple-sanctuary.png"')
    expect(javascript).to include('LOCATION_ARTS[state.scene]')
    expect(javascript).to include('elements.locationArt.style.transform = `scale(${scale.toFixed(2)})`')
    expect(javascript).to include('elements.locationArt.style.transform = ""')
    expect(javascript.scan('elements.locationArt.style.transform = ""').length).to eq 2
    expect(javascript).to include('"has-location-art"')
    expect(javascript).not_to include('function isLoggableLine(line)')
    expect(javascript).to include('let messageLogLines = []')
    expect(javascript).to include('const events = eventsFromPayload(payload)')
    expect(javascript).to include('if (Array.isArray(payload.events)) return payload.events')
    expect(javascript).to include('messageLogLines = [...messageLogLines, ...eventLines].slice(-80)')
    expect(javascript).to include('const visibleLines = messageLogLines.length ? messageLogLines : [" "]')
    expect(javascript).not_to include('state.history')
    expect(javascript).to include('function quickCommandsFor(state)')
    expect(javascript).to include('contextCommands: document.querySelector("#context-commands")')
    expect(javascript).to include('autoSpeedButtons: document.querySelectorAll(".map-speed-button[data-auto-speed]")')
    expect(javascript).to include('shopOverlay: document.querySelector("#shop-overlay")')
    expect(javascript).to include('playerTradeList: document.querySelector("#player-trade-list")')
    expect(javascript).to include('merchantTradeList: document.querySelector("#merchant-trade-list")')
    expect(javascript).to include('autoExploreToggle: document.querySelector("#auto-explore-toggle")')
    expect(javascript).to include('autoExploreStatus: document.querySelector("#auto-explore-status")')
    expect(javascript).to include('renderContextCommands(state)')
    expect(javascript).to include('renderShopOverlay(state)')
    expect(javascript).to include('function renderContextCommands(state = currentState)')
    expect(javascript).to include('button.disabled = Boolean(disabled)')
    expect(javascript).to include('button.addEventListener("click", () => handleContextCommand(command))')
    expect(javascript).to include('function handleContextCommand(command)')
    expect(javascript).to include('if (command === "shop")')
    expect(javascript).to include('function autoExploreCommands(state)')
    expect(javascript).to include('if (state.scene === "ruins") return autoExploreCommands(state)')
    expect(javascript).to include('["Explore", "auto explore", "primary"]')
    expect(javascript).to include('["Go Town", "auto town", "primary"]')
    expect(javascript).to include('["Go Deep", "auto descent", "primary"]')
    expect(javascript).to include('function autoExploreDescentFound(state)')
    expect(javascript).to include('["Taverna", "go tavern"]')
    expect(javascript).to include('["Ferreiro", "go blacksmith"]')
    expect(javascript).to include('["Loja", "shop", "primary"]')
    expect(javascript).not_to include('["Comprar", "buy rusty dagger", "primary"]')
    expect(javascript).not_to include('["Vender", "sell"]')
    expect(javascript).to include('button.setAttribute("aria-label", accessibleLabel)')
    expect(javascript).not_to include('const battleItemCommands = state.battle?.active ? suggestedItemCommands(state.player) : []')
    expect(javascript).to include('...suggestedItemCommands(state.player)')
    expect(javascript).not_to include('["Inventario", "inventory"]')
    expect(javascript).not_to include('["Magias", "spellbook"]')
    expect(javascript).not_to include('Modo Game')
    expect(javascript).not_to include('function inputModeCommand(state)')
    expect(javascript).to include('selectTab("inventory")')
    expect(javascript).to include('function selectTab(name)')
    expect(javascript).not_to include('selectTab("inventory", { syncTop: false });\n    activateTopTab(0);\n    elements.commandInput.focus();')
    expect(javascript).to include('state.dungeon?.nearby_loot')
    expect(javascript).to include('const autoExplore = {')
    expect(javascript).to include('function startAutoExplore(goal = "explore")')
    expect(javascript).to include('function stopAutoExplore(reason = "stopped")')
    expect(javascript).to include('function autoExploreGoalStatus(goal)')
    expect(javascript).to include('function scheduleAutoExplore()')
    expect(javascript).to include('function autoExploreDelay()')
    expect(javascript).to include('AUTO_EXPLORE_DELAY_MS / autoExplore.speedMultiplier')
    expect(javascript).to include('function setAutoExploreSpeed(multiplier)')
    expect(javascript).to include('elements.autoSpeedButtons.forEach(button =>')
    expect(javascript).to include('button.addEventListener("click", () => setAutoExploreSpeed(Number(button.dataset.autoSpeed)))')
    expect(javascript).to include('function nextAutoExploreDecision(state)')
    expect(javascript).to include('function autoExploreLevelCompleteDecision(state)')
    expect(javascript).to include('function nextAutoExploreGoalDecision(state)')
    expect(javascript).to include('function autoExploreGoalPosition(state)')
    expect(javascript).to include('function nextAutoExploreTargetDirection(state, target)')
    expect(javascript).to include('function nextDirectionAwayFromAutoExploreTarget(state, position)')
    expect(javascript).to include('function nextAutoExploreDirection(state)')
    expect(javascript).to include('function autoExploreHealingSpell(state)')
    expect(javascript).to include('function autoExploreHealingPotion(state)')
    expect(javascript).to include('function autoExploreNeedsHealing(state)')
    expect(javascript).to include('memoryGameId: null')
    expect(javascript).to include('knownCells: new Map()')
    expect(javascript).to include('knownLevel: null')
    expect(javascript).to include('currentPath: []')
    expect(javascript).to include('continueAfterDescent: false')
    expect(javascript).to include('continuousDescent: false')
    expect(javascript).to include('speedMultiplier: 1')
    expect(javascript).to include('restoreAutoExploreMemory(state)')
    expect(javascript).to include('function updateAutoExploreKnowledge(state)')
    expect(javascript).to include('saveAutoExploreMemory()')
    expect(javascript).to include('function visibleEnemyPosition(state)')
    expect(javascript).to include('function nextDirectionTowardVisibleEnemy(state, enemyPosition)')
    expect(javascript).to include('function pathToNearestAutoExploreFrontier(state, start)')
    expect(javascript).to include('function shortestAutoExplorePath(start, targets, options = {})')
    expect(javascript).to include('function autoExploreFrontierPositions(state)')
    expect(javascript).to include('function unexploredDirectionFrom(state, position)')
    expect(javascript).to include('function findAutoExplorePath(start, goal, options = {})')
    expect(javascript).to include('function autoExploreNeighbors(key, goalKey = null, options = {})')
    expect(javascript).to include('function walkableAutoExploreGoalKey(key, options = {})')
    expect(javascript).to include('function reconstructAutoExplorePath(cameFrom, currentKey)')
    expect(javascript).to include('if (api.pendingAction)')
    expect(javascript).to include('return { command: `cast ${healingSpell.name}`, status: "Auto: healing" }')
    expect(javascript).to include('return { command: `use ${healingPotion.name}`, status: "Auto: healing" }')
    expect(javascript).to include('return health.current / health.max < 0.2')
    expect(javascript).to include('spell.kind === "healing"')
    expect(javascript).to include('item.name === "potion of heal"')
    expect(javascript).to include('command: spell ? `cast ${spell.name}` : "attack"')
    expect(javascript).to include('const visibleEnemy = visibleEnemyPosition(state)')
    expect(javascript).to include('status: "Auto: hunting"')
    expect(javascript).to include('if (autoExplore.goal !== "explore") return nextAutoExploreGoalDecision(state)')
    expect(javascript).to include('if (autoExplore.goal === "descent" && state.dungeon?.nearby_loot)')
    expect(javascript).to include('if (autoExplore.goal === "descent" && !autoExploreDescentFound(state))')
    expect(javascript).to include('function nextAutoExploreDeepExplorationDecision(state)')
    expect(javascript).to include('status: "Auto: seeking descent"')
    expect(javascript).to include('status: autoExploreGoalStatus(autoExplore.goal)')
    expect(javascript).to include('shortestAutoExplorePath(position, [target], { allowTransitionGoal: true })')
    expect(javascript).to include('return { command: "loot", status: "Auto: looting" }')
    expect(javascript).to include('if (isLevelTransitionPosition(state, nextPosition)) return false')
    expect(javascript).to include('const entitySymbols = { player: "x", enemy: "E", loot: "@", portal: "P", ascent: "<", descent: ">" }')
    expect(javascript).to include('state.dungeon?.entrance_portal || state.dungeon?.ascent')
    expect(javascript).to include('["ascent", "descent", "portal"].includes(entity.type)')
    expect(javascript).to include('samePosition(position, state.dungeon?.ascent)')
    expect(javascript).to include('samePosition(position, state.dungeon?.descent)')
    expect(javascript).to include('samePosition(position, state.dungeon?.entrance_portal)')
    expect(javascript).to include('function isBlockExitPosition(state, position, direction)')
    expect(javascript).to include('stopAutoExplore("level complete")')
    expect(javascript).to include('function setAutoExploreGoal(goal)')
    expect(javascript).to include('function manualAutoExploreGoal(command)')
    expect(javascript).to include('if (normalizedCommand === "go town") return "town"')
    expect(javascript).to include('function autoExploreGoalReached(state)')
    expect(javascript).to include('function continueAutoExploreAfterDescent(state)')
    expect(javascript).to include('stopAutoExplore("town reached")')
    expect(javascript).to include('autoExplore.continueAfterDescent = goal === "descent"')
    expect(javascript).to include('autoExplore.continuousDescent = goal === "descent"')
    expect(javascript).to include('autoExplore.goal = autoExplore.continuousDescent ? "descent" : "explore"')
    expect(javascript).to include('autoExplore.continueAfterDescent = autoExplore.continuousDescent')
    expect(javascript).to include('stopAutoExplore("level descended")')
    expect(javascript).to include('elements.autoExploreToggle.addEventListener("click"')
    expect(javascript).to include('commandValue: inventoryCommandValue(item)')
    expect(javascript).to include('function inventoryCommandValue(item)')
    expect(javascript).to include('function inventoryItemLabel(item)')
    expect(javascript).to include('function openShop()')
    expect(javascript).to include('function renderTradeItems(target, items, mode)')
    expect(javascript).to include('function tradeItemCopy(item, mode)')
    expect(javascript).to include('function tradeItemQuantityControls(item, mode)')
    expect(javascript).to include('const TRADE_QUANTITY_HOLD_DELAY_MS = 350')
    expect(javascript).to include('const TRADE_QUANTITY_HOLD_INTERVAL_MS = 90')
    expect(javascript).to include('function bindTradeQuantityStep(button, mode, item, direction)')
    expect(javascript).to include('button.addEventListener("pointerdown", event =>')
    expect(javascript).to include('repeatTimer = window.setInterval(step, TRADE_QUANTITY_HOLD_INTERVAL_MS)')
    expect(javascript).to include('function setTradeQuantity(mode, item, nextQuantity)')
    expect(javascript).to include('function tradePayload(selection)')
    expect(javascript).to include('buy: tradePayload(shopTrade.buy)')
    expect(javascript).to include('function tradeItemDescription(item)')
    expect(javascript).to include('function tradeTotals(state)')
    expect(javascript).to include('async function submitTradeSelection()')
    expect(javascript).to include('type: "trade"')
    expect(javascript).to include('return `${name} (DMG ${item.attack})`')
    expect(javascript).to include('return `${name} (DEF ${item.defense})`')
    expect(javascript).to include('return `equip ${item.name}`')
    expect(javascript).to include('return `use ${item.name}`')
    expect(javascript).to include('return `drop ${item.name}`')
    expect(javascript).to include('label: `${item.quantity || 1}x ${inventoryItemLabel(item)}`')
    expect(javascript).to include('meta: item.type || ""')
    expect(javascript).to include('commandValue: spell.name')
    expect(javascript).to include('button.className = "collection-item-command"')
    expect(javascript).to include('button.addEventListener("click", () => fillCommandInput(details.commandValue || details.label))')
    expect(javascript).to include('function fillCommandInput(value)')
    expect(javascript).to include('elements.commandInput.setSelectionRange(value.length, value.length)')
    expect(javascript).to include('state.pending?.confirmation')
    expect(javascript).to include('function suggestedItemCommands(player)')
    expect(javascript).to include('equippedNames.includes(item.name)')
    expect(javascript).to include('function updateCommandPlaceholder(state)')
    expect(javascript).to include('elements.commandInput.placeholder = "reload"')
    expect(javascript).to include('recarregar: "reload"')
    expect(javascript).to include('"reload"')
    expect(javascript).to include('const commandHistory')
    expect(javascript).to include('function recordCommand(command)')
    expect(javascript).to include('function recallCommand(direction)')
    expect(javascript).to include('function submitCommand(command, options = {})')
    expect(javascript).to include('!autoCompatibleManualCommand(normalizedCommand)')
    expect(javascript).to include('function autoCompatibleManualCommand(command)')
    expect(javascript).to include('/^(equip|use)\\b/i.test(command.trim())')
    expect(javascript).to include('if (options.source !== "auto") elements.commandInput.value = ""')
    expect(javascript).to include('event.key === "ArrowUp"')
    expect(javascript).to include('event.key === "ArrowDown"')
    expect(javascript).to include('elements.statusValue.classList.toggle("status-alert"')
    expect(javascript).to include('elements.statusValue.classList.toggle("status-clear"')
    expect(javascript).to include('renderEquipmentPanel(player)')
    expect(javascript).to include('function renderEquipmentPanel(player)')
    expect(javascript).to include('gold.className = "gold-line"')
    expect(javascript).to include('gold.textContent = `Gold    ${player.gold}`')
    expect(javascript).to include('equipmentLine("ARM", player.equipment.weapon, "Unarmed", "DMG", "attack")')
    expect(javascript).to include('equipmentLine("DEF", player.equipment.armor, "No armor", "DEF", "defense")')
    expect(javascript).to include('function equipmentLine(label, item, fallbackName, statLabel, statKey)')
    expect(javascript).to include('renderClassProgress(player.skills)')
    expect(javascript).to include('function renderClassProgress(skills = {})')
    expect(javascript).to include('player.current_class || "Adventurer"')
    expect(javascript).to include('plainAsciiBar(skill.xp, skill.next_level_xp)')
    expect(javascript).to include('row.className = "class-row"')
    expect(javascript).to include('function plainAsciiBar(current, max)')
    expect(javascript).to include('const width = 10')
    expect(javascript).not_to include('className = "class-xp"')
    expect(javascript).to include('function renderEnemyStatus(battle)')
    expect(javascript).to include('elements.enemyPanel.classList.toggle("hidden", !enemy)')
    expect(javascript).to include('function playCombatFeedback(events)')
    expect(javascript).to include('function combatExchanges(events)')
    expect(javascript).to include('function combatEffectFromText(text)')
    expect(javascript).to include('event.effect || combatEffectFromText(event.text)')
    expect(javascript).to include('dungeonMapRenderer.animateAttack(exchange.source, exchange.effect)')
    expect(javascript).to include('dungeonMapRenderer.clearAttackAnimation()')
    expect(javascript).not_to include('BTTL ${battle}')
    expect(javascript).not_to include('MODE ${state.input_mode.toUpperCase()}')
    expect(javascript).not_to include('state.input_mode')
    expect(javascript).to include('locationPanels')
    expect(styles).to include('"https://fonts.googleapis.com/css2?family=Bitcount+Single&display=swap"')
    expect(styles).to include('--mono: "Bitcount Single"')
    expect(styles).to include('.map-stage.has-location-art')
    expect(styles).to include('.map-zoom-controls')
    expect(styles).to include('.map-speed-button')
    expect(styles).to include('.map-speed-button[aria-pressed="true"]')
    expect(styles).to include('.map-zoom-button')
    expect(styles).to include('background: #000')
    expect(styles).to include('object-fit: contain')
    expect(styles).to include('transform-origin: center')
    expect(styles).to include('.status-row')
    expect(styles).to include('.status-alert')
    expect(styles).to include('.class-output')
    expect(styles).to include('.class-row')
    expect(styles).not_to include('.class-xp')
    expect(styles).to include('.enemy-panel')
    expect(styles).to include('.commands-panel')
    expect(styles).to include('.auto-explore-controls')
    expect(styles).to include('.auto-explore-controls button[aria-pressed="true"]')
    expect(styles).to include('.context-commands')
    expect(styles).to include('.context-commands button::after')
    expect(styles).to include('.gold-line')
    expect(styles).to include('color: var(--amber)')
    expect(styles).to include('.collection-item-command')
    expect(styles).to include('.shop-overlay')
    expect(styles).to include('.shop-grid')
    expect(styles).to include('.trade-item')
    expect(styles).to include('.trade-item.selected')
    expect(styles).to include('.trade-quantity')
    expect(styles).to include('.quantity-step')
    expect(styles).to include('.item-line')
    expect(styles).to include('.item-description')
    expect(styles).to include('.trade-summary')
    expect(styles).to include('justify-self: end')
    expect(styles).to include('white-space: nowrap')
    expect(styles).to include('.hidden')
    expect(styles).not_to include('.run-stats')
    expect(styles).not_to include('.attribute-grid')
    expect(renderer).to include('globalThis.DungeonMapRenderer')
    expect(renderer).to include('"/assets/tilesets/original-dungeon-tileset.png"')
    expect(renderer).to include('const TILESET_SOURCE_SIZE = { width: 1254, height: 1254 }')
    expect(renderer).to include('const TILESET_SOURCE_COLUMNS = [')
    expect(renderer).to include('{ x: 5, width: 151 }')
    expect(renderer).to include('{ x: 1098, width: 151 }')
    expect(renderer).to include('const TILESET_SOURCE_ROWS = [')
    expect(renderer).to include('{ y: 5, height: 304 }')
    expect(renderer).to include('{ y: 944, height: 305 }')
    expect(renderer).to include('const TILESET_REFERENCE_CELL = { width: 151, height: 308 }')
    expect(renderer).to include('const TILE_WIDTH = 48')
    expect(renderer).to include('const TILE_HEIGHT = Math.round(TILE_WIDTH * (TILESET_REFERENCE_CELL.height / TILESET_REFERENCE_CELL.width))')
    expect(renderer).to include('const ENEMY_HEIGHT_SCALE = 1.5')
    expect(renderer).to include('function sourceRectForTile(tileset, tileX, tileY)')
    expect(renderer).not_to include('tileset.naturalWidth / TILESET_COLUMNS')
    expect(renderer).to include('const ENTITY_SPRITES = {')
    expect(renderer).to include('source: { x: 13, y: 358, width: 132, height: 160 }')
    expect(renderer).to include('function drawEntityTile(context, tileset, tileName, x, y)')
    expect(renderer).to include('drawEnemyImage(context, image, renderer.ready ? tileset : null, enemy.x, enemy.y)')
    expect(renderer).to include('function drawEnemyImage(context, image, tileset, x, y)')
    expect(renderer).to include('? enemySpriteTargetRect(tileset, image, x, y)')
    expect(renderer).to include('function entitySpriteSourceRect(tileset, tileName)')
    expect(renderer).to include('function entitySpriteTargetRect(tileset, tileName, x, y)')
    expect(renderer).to include('function enemySpriteTargetRect(tileset, image, x, y)')
    expect(renderer).to include('const height = playerTarget.height * ENEMY_HEIGHT_SCALE')
    expect(renderer).to include('function spriteTargetRect(tileset, tileName, sourceRect, x, y)')
    expect(renderer).to include('function containedTileRect(sourceWidth, sourceHeight, x, y)')
    expect(renderer).to include('drawEntityTile(context, renderer.ready ? tileset : null, tileName, entity.x, entity.y)')
    expect(renderer).to include('function tileNameForSymbol(rows, symbol, x, y)')
    expect(renderer).to include('function wallTileName(rows, x, y)')
    expect(renderer).to include('function openTerrainAt(rows, x, y)')
    expect(renderer).to include('if (southOpen) return "wallTop"')
    expect(renderer).to include('if (eastOpen && !westOpen) return "wallLeft"')
    expect(renderer).to include('if (westOpen && !eastOpen) return "wallRight"')
    expect(renderer).to include('return ((x + y) % 5 === 0) ? "wallTop" : "wall"')
    expect(renderer).to include('"#": "wall"')
    expect(renderer).to include('".": "floor"')
    expect(renderer).to include('" ": "floor"')
    expect(renderer).to include('"?": "fog"')
    expect(renderer).to include('portal: [7, 3]')
    expect(renderer).to include('"/assets/enemies/enemies.json"')
    expect(renderer).to include('function drawFog(context, x, y)')
    expect(renderer).to include('drawFog(context, x, y)')
    expect(renderer).to include('animateAttack(source, effect = "magic")')
    expect(renderer).to include('clearAttackAnimation()')
    expect(renderer).to include('function drawAttackTrace(context, from, to, progress, source, effect = "magic")')
    expect(renderer).to include('function drawMagicTrace(context, from, to, progress, source)')
    expect(renderer).to include('function drawSlashTrace(context, from, to, progress, source)')
    expect(renderer).to include('function drawSlashLine(context, center, angle, length)')
    expect(renderer).to include('function drawDeathOverlay(context, canvas)')
    expect(renderer).to include('drawDeathOverlay(context, canvas)')
    expect(renderer).to include('fillText("Voce Morreu!"')
    expect(renderer).to include('function rowsFromViewport(viewport)')
    expect(renderer).to include('function drawEntities(context, renderer, enemyImages, tileset, entities)')
    expect(renderer).to include('drawEntities(context, renderer, enemyImages, tileset, entities)')
    expect(renderer).to include('const ENTITY_FALLBACK_COLORS')
    expect(renderer).to include('player: "#f8f5c7"')
    expect(renderer).to include('const ENTITY_TILES')
    expect(renderer).to include('player: "player"')
    expect(renderer).to include('portal: "portal"')
    expect(renderer).to include('ascent: "stairsUp"')
    expect(renderer).to include('descent: "stairsDown"')
    expect(renderer).to include('loot: "lootBag"')
    expect(renderer).to include('image.src = entry.sprite')
  end
end
