require 'spec_helper'

RSpec.describe "Frontend assets" do
  let(:root) { File.expand_path("../..", __dir__) }
  let(:frontend_root) { File.join(root, "frontend") }
  let(:public_root) { File.join(frontend_root, "public") }
  let(:source_root) { File.join(frontend_root, "src") }

  it "checks in the Vite React entrypoints, renderer bridge, and game assets" do
    expect(File).to exist(File.join(frontend_root, "index.html"))
    expect(File).to exist(File.join(frontend_root, "package.json"))
    expect(File).to exist(File.join(frontend_root, "vite.config.ts"))
    expect(File).to exist(File.join(frontend_root, "nginx.conf"))
    expect(File).to exist(File.join(source_root, "main.tsx"))
    expect(File).to exist(File.join(source_root, "App.tsx"))
    expect(File).to exist(File.join(source_root, "App.css"))
    expect(File).to exist(File.join(source_root, "index.css"))
    expect(File).to exist(File.join(public_root, "map_renderer.js"))
    expect(File).to exist(File.join(public_root, "assets/tilesets/original-dungeon-tileset.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/village-hub.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/tavern-interior.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/merchant-district.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/blacksmith-workshop.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/armorsmith-shop.png"))
    expect(File).to exist(File.join(public_root, "assets/locations/temple-sanctuary.png"))
    expect(File).to exist(File.join(public_root, "assets/figma/dungeon-terminal-reference.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Adventurer.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Blademaster.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Dragoon.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Nightblade.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Arcanist.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Warlord.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Duelist.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Mystic.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Spellblade.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Warden.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Skirmisher.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Battlemage.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Sentinel.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Hexblade.png"))
    expect(File).to exist(File.join(public_root, "assets/atlas/class/Ranger.png"))
    expect(File).not_to exist(File.join(public_root, "assets/classes"))
    expect(File).not_to exist(File.join(public_root, "app.js"))
    expect(File).not_to exist(File.join(public_root, "styles.css"))
  end

  it "checks in the generated Adventurer class atlas" do
    sheet = File.binread(File.join(public_root, "assets/atlas/class/Adventurer.png"), 33)

    expect(sheet.byteslice(0, 8)).to eq("\x89PNG\r\n\x1A\n".b)
    expect(sheet.byteslice(16, 8).unpack("NN")).to eq([874, 1799])
    expect(sheet.byteslice(24, 2).unpack("CC")).to eq([8, 6])
  end

  it "wires the React frontend to game API, WebSocket, and modular panels" do
    html = File.read(File.join(frontend_root, "index.html"))
    app = File.read(File.join(source_root, "App.tsx"))
    session_hook = File.read(File.join(source_root, "hooks/useGameSession.ts"))
    auto_explore_hook = File.read(File.join(source_root, "hooks/useAutoExplore.ts"))
    api = File.read(File.join(source_root, "lib/gameApi.ts"))
    commands = File.read(File.join(source_root, "lib/commands.ts"))
    shell = File.read(File.join(source_root, "components/game/GameShell.tsx"))
    command_panel = File.read(File.join(source_root, "components/game/CommandPanel.tsx"))
    map_panel = File.read(File.join(source_root, "components/game/MapPanel.tsx"))
    trade_overlay = File.read(File.join(source_root, "components/game/TradeOverlay.tsx"))
    vite_config = File.read(File.join(frontend_root, "vite.config.ts"))
    dockerfile = File.read(File.join(root, "Dockerfile"))

    expect(html).to include('<script src="/map_renderer.js"></script>')
    expect(html).to include('<script type="module" src="/src/main.tsx"></script>')
    expect(html).to include('<title>Text Adventures</title>')
    expect(app).to include('useGameSession()')
    expect(app).to include('useAutoExplore({')
    expect(app).to include('actionFromCommand(normalized)')
    expect(app).to include('isShopCommand(normalized)')
    expect(app).to include('manualAutoExploreGoal(normalized')
    expect(app).to include('autoCompatibleManualCommand(normalized)')
    expect(app).to include('setPlayerDirection(nextDirection)')
    expect(shell).to include('<CharacterPanel state={state} />')
    expect(shell).to include('<MapPanel')
    expect(shell).to include('<CollectionPanel')
    expect(shell).to include('<CommandPanel')
    expect(shell).to include('<CommandBar')
    expect(shell).to include('<TradeOverlay')
    expect(api).to include('fetch("/api/games"')
    expect(api).to include('fetch(`/api/games/${encodeURIComponent(gameId)}`)')
    expect(api).to include('fetch(`/api/games/${encodeURIComponent(gameId)}/actions`')
    expect(api).to include('socketUrl(gameId: string)')
    expect(session_hook).to include('new WebSocket(socketUrl(gameId))')
    expect(session_hook).to include('socketActionPayload(action)')
    expect(session_hook).to include('parseSocketMessage(String(event.data))')
    expect(session_hook).to include('mergeStatePatch(stateRef.current, message.patch)')
    expect(session_hook).to include('executeAction(gameId, action)')
    expect(session_hook).to include('rememberGameId(nextGameId)')
    expect(commands).to include('quickCommandsFor(state: GameState | null)')
    expect(commands).to include('manualAutoExploreGoal(')
    expect(commands).to include('autoCompatibleManualCommand(')
    expect(commands).to include('{ label: "Attack", command: "attack", kind: "primary" }')
    expect(commands).to include('{ label: "Shop", command: "shop", kind: "primary" }')
    expect(auto_explore_hook).to include('AUTO_EXPLORE_MEMORY_KEY_PREFIX')
    expect(auto_explore_hook).to include('shortestAutoExplorePath(')
    expect(auto_explore_hook).to include('nextAutoExploreGoalDecision()')
    expect(auto_explore_hook).to include('autoExploreHealingAction()')
    expect(command_panel).to include('autoExploreCommands()')
    expect(command_panel).to include('Auto speed')
    expect(command_panel).to include('autoExplore.setGoal(autoGoalFromCommand(command.command))')
    expect(map_panel).to include('window.DungeonMapRenderer.create(canvasRef.current)')
    expect(map_panel).to include('rendererRef.current.render(viewport')
    expect(map_panel).to include('renderer.animateAttack(exchange.source, exchange.effect)')
    expect(map_panel).to include('textRowsFromViewport(viewport)')
    expect(map_panel).to include('Revive in Town')
    expect(map_panel).to include('New Game')
    expect(trade_overlay).to include('type: "trade"')
    expect(trade_overlay).to include('tradePayload(prunedSelections.buy)')
    expect(trade_overlay).to include('Sell all junk')
    expect(vite_config).to include("'/api'")
    expect(vite_config).to include("target: 'http://127.0.0.1:4567'")
    expect(vite_config).to include("'/ws'")
    expect(vite_config).to include('ws: true')
    expect(dockerfile).to include('FROM node:alpine AS frontend-build')
    expect(dockerfile).to include('RUN pnpm build')
    expect(dockerfile).to include('COPY --from=frontend-build /text_adventures/frontend/dist /usr/share/nginx/html')
    expect(api).not_to include('/commands')
  end
end
